### ISSUE TITLE
improve appearance for vector plots

### ISSUE THREAD

**Issue by danlipsa** [CDAT/vcs#133] opened 2017-02-28 19:33 UTC
Compare output from vcs
![test_vcs_basic_streamline_transparent](https://cloud.githubusercontent.com/assets/6180727/23436976/6cffe1b4-fdda-11e6-900a-ffc17883c692.png)
to output from ParaView
![vector](https://cloud.githubusercontent.com/assets/6180727/23436951/50de30b2-fdda-11e6-9dda-613e120d15fa.png)

**Comment by durack1** [comment] 2017-02-28 20:17
@danlipsa looks like you pressed save before the uploading had finished..

**Comment by danlipsa** [comment] 2017-02-28 21:02
@durack1 github is having troubles uploading pngs. It says: "Something went really wrong, and we can’t process that file." I tried with both chrome and safari. I will try this tomorrow.

**Comment by danlipsa** [comment] 2017-02-28 22:20
@durack1 Maybe this is the reason:
http://www.usatoday.com/story/tech/news/2017/02/28/amazons-cloud-service-goes-down-sites-scramble/98530914/

**Comment by danlipsa** [comment] 2017-02-28 22:22
@durack1 Now things are back to normal.

**Comment by aashish24** [comment] 2017-02-28 22:28
> Compare output from vcs

@danlipsa two things: 

1. Spacing 
2. Scaling

You can control these two in vcs but I agree that by default we do not do a good job with it. And hence we draw too many and too small. Also, we do not color them.

**Comment by danlipsa** [comment] 2017-02-28 22:35
@aashish24 I think the reasons vectors look worst in vcs are:
- the seeds are random in paraview - are uniformly spaced in vcs
- paraview's arrows are 3D so they can use lighting.
With these two improvements we should get similar results with ParaView.

Of course, ParaView also colors the arrows and scales them with the vector magnitude.

**Comment by durack1** [comment] 2017-02-28 22:55
@danlipsa having the ability to plot the second (paraview) image using `VCS` would be pretty cool, I agree that it's a prettier format.. It would also be nice to be able to plot the old versions too.. so a "3d vector (paraview)" along with a "vector (current vcs default)"

**Comment by chaosphere2112** [comment] 2017-02-28 23:06
@danlipsa @durack1 We can already do 3D vectors (by using the cunningly titled "3d_vector" graphics method, courtesy of our friends at NASA). Changing the 2D vectors to be the same as the 3D vectors would be a bit odd.

**Comment by durack1** [comment] 2017-02-28 23:08
@chaosphere2112 are there any examples of these in the gallery? If no, it would be great to add them.. And how do they compare to the paraview version above?

**Comment by chaosphere2112** [comment] 2017-02-28 23:33
![screen shot 2017-02-28 at 3 32 10 pm](https://cloud.githubusercontent.com/assets/718512/23439373/1d36104a-fdcb-11e6-8177-774aff8910bf.png)

This is with a minimal amount of futzing. It allows interactive selection of the vertical level, and a number of other customizations.

There is an example in the gallery: http://uvcdat.llnl.gov/examples/vcs3D_wnd_vector.html

**Comment by durack1** [comment] 2017-03-01 00:04
@chaosphere2112 nice! The page http://uvcdat.llnl.gov/examples/vcs3D_wnd_vector.html doesn't seem to have a valid image to me, a permissions issue maybe?

**Comment by chaosphere2112** [comment] 2017-03-01 00:16
Looks fine to me... permissions shouldn't break across different computers. Try reloading?

**Comment by durack1** [comment] 2017-03-01 00:18
@chaosphere2112 weird, whatever you did it's fine now..

**Comment by jypeter** [comment] 2017-03-01 08:12
Guys, remember that for a **2D publication with precise results**, we rather need something like the _old but trusted_ vcs plot, where you can easily have axes, titles, variable name, min/max, etc... If the data is too dense, I usually sub-sample the data with  _x.plot(vect_method, var[::5, ::5])_ and possibly use slightly longer arrows

I don't have that many plots with vectors in store, but the following one, from 2008, does not look that bad
![tas_wind_pmip2_0k_oa_jja](https://cloud.githubusercontent.com/assets/2785573/23450989/2e97a676-fe5e-11e6-8d1e-c56dda394075.png)

On the other hand, it's true that being able to specify the color of the individual vectors could be useful in some cases.

I have also added below a vector plot I made a year ago, using... basemap

![jjas_wind950](https://cloud.githubusercontent.com/assets/2785573/23451085/a2b905ea-fe5e-11e6-8ee2-493a5ffc3e9b.png)

**Comment by danlipsa** [comment] 2017-03-01 14:38
> There is an example in the gallery: http://uvcdat.llnl.gov/examples/vcs3D_wnd_vector.html

@chaosphere2112 Nice! Can you have axes labels as well? Lighting seems off in that example.

**Comment by danlipsa** [comment] 2017-03-01 16:29
@jypeter Thanks for the feedback. @aashish24 @doutriaux1 To improve our vector plots compared with basemap seems we need to (besides spacing and scaling):
- Use a triangle for the arrow head instead of two lines
- Smaller vectors keep their arrow head as much as possible (vcs scales the whole arrow and so the arrow head becomes very small)
- The legend in vcs can be improved
- I think the seeds in basemap are random - you cannot really see a grid where each arrow starts, but you can see that in vcs.
- I think 3D arrows can also be an option, as long as we can do axes labels.

**Comment by danlipsa** [comment] 2017-03-01 16:34
@aashish24 @doutriaux1 It seems you you need to sub-sample the data to get the right spacing. Is there an option to the vector plot to specify spacing?

**Comment by jypeter** [comment] 2017-04-27 12:40
For the record, I have already spent a full frustrating day trying to make a nice vector plot with 2.8.0: #187 

Maybe I should have put my rambling in this thread

**Comment by doutriaux1** [comment] 2019-04-18 19:56
duplicate of #187

**Closed by doutriaux1** 2019-04-18 19:56 UTC
Labels: enhancement, question
