### ISSUE TITLE
vcs cannot go back into interact mode

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#86] opened 2016-11-23 16:17 UTC
```
In [1]: dv3d = vcs.get3d_scalar('Hovmoller3D')

In [2]: x.plot(s,dv3d)
Warning, can't open data file 'None'
initCamera: Camera => ((0.0, 0.0, 540.0), (0.0, 0.0, 0.0), (0.0, 1.0, 0.0)) 
Out[2]: <vcs.displayplot.Dp at 0x11c48f320>

In [3]: x.interact()
/lgm/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VTKPlots.py:87: UserWarning: Press 'Q' to exit interactive mode and continue script execution
  warnings.warn("Press 'Q' to exit interactive mode and continue script execution")
 saved state data to file  <closed file '/lgm/uvcdat/2.2.0/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/DV3D/data/state.txt', mode 'w' at 0x11c47dc90>

In [3]: dv3d.list()
 ---------- DV3D (Gfdv3d) member (attribute) listings ---------
name = Hovmoller3D
axes = xyt
ToggleVolumePlot = None
BasemapOpacity = '[0.5]'
Camera = "{'Position': (-262.50460102175333, -326.28088967728246, 340.92831427414325), 'ViewUp': (-0.019506706986772843, 0.7297785655923166, 0.6834052484321093), 'FocalPoint': (0.0, 0.0, 0.0)}"
PointSize = None
Configure = None
ScaleColormap = '[0.0, 100.0, 1]'
ChooseColormap = None
ToggleSurfacePlot = None
SliceThickness = None
ScaleOpacity = '[1.0, 1.0]'
Colorbar = None
ToggleClipping = None
Animation = '[0.0]'
ZSlider = '( [0.31786257636913323], vcs.on )'
IsosurfaceValue = '[50.0]'
YSlider = '[-90.0]'
ScaleTransferFunction = '[0.0, 100.0, 1]'
VerticalScaling = '[1.0]'
XSlider = '[-180.0]'
ToggleSphericalProj = None

In [4]: dv3d.ToggleSurfacePlot = vcs.on

In [5]: x.interact()
```

At that point resizing the windows hangs the system comletely

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1295

**Comment by durack1** [comment] 2017-04-13 15:46
@doutriaux1 I am hitting a similar problem with `vcs` plots and `x.interact()` preventing me from being able to close the opened canvas.. The only path forward is to kill the active ipython session - this is bad

**Comment by doutriaux1** [comment] 2017-04-13 15:59
@durack1 if you have x.interact() you then need to hit `Q` while the windo is active to keep going. Are you doing this?

**Comment by durack1** [comment] 2017-04-13 16:01
@doutriaux1 yep, hitting 'Q' returns the focus back to the console, but the canvas becomes unusable..

**Comment by doutriaux1** [comment] 2017-04-13 16:03
let's take a look next week

**Comment by durack1** [comment] 2017-04-26 22:09
@doutriaux1 this was the issue we were discussing, however, it's `vcs` not `dv3d` that is having the issue, I have renamed the issue to reflect this

**Comment by durack1** [comment] 2017-05-03 18:09
@doutriaux1 @danlipsa @aashish24 just fyi, this bug is preventing me from using `vcs` in interactive data discovery.. Which is really unfortunate, as I would prefer to use it.. `Matplotlib` on the other hand can successfully open and close interactive plotting windows, so I'm forced to use that instead

**Comment by danlipsa** [comment] 2017-05-04 16:36
@durack1 Can you provide us the steps to reproduce the problem. I tried what Sam wrote but I cannot reproduce the problem.

**Comment by durack1** [comment] 2017-05-10 01:13
@danlipsa I haven't checked this in a v2.10 ipython console, but this is what didn't work for me last time:
```python
import vcs
import numpy

mat = np.zeros([5,5])
x = vcs.init()
y = vcs.init()
x.meshfill(mat)
y.meshfill(mat)
x.clear()
y.clear()
x.close() ; # This leads to a zombie window that doesn't die until the ipython session is killed
y.close() ; # Same here
```

**Comment by danlipsa** [comment] 2017-05-10 13:30
@durack1 @doutriaux1 With 2.10 I get
<pre>
>>> x.meshfill(mat)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/danlipsa/anaconda/envs/2.10/lib/python2.7/site-packages/vcs/Canvas.py", line 1385, in meshfill
    arglist = _determine_arg_list('meshfill', args)
  File "/Users/danlipsa/anaconda/envs/2.10/lib/python2.7/site-packages/vcs/Canvas.py", line 264, in _determine_arg_list
    raise vcsError("Meshfill requires 2 slab if first slab doesn't have a "
vcs.error.vcsError: Meshfill requires 2 slab if first slab doesn't have a Rectilinear, Curvilinear or Generic Grid type
</pre>

**Comment by durack1** [comment] 2017-05-11 00:42
@danlipsa try this:
```python
(uvcdat2100) duro@ocean:[160427_CMIP6_Forcing]:[5711]> ipython
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11)
Type "copyright", "credits" or "license" for more information.
IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
In [1]: import cdms2,vcs
In [2]: f = '/export/durack1/170123_CDAT_scripts/siconc_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-1_gn_187001.nc'
In [3]: fH = cdms2.open(f)
In [4]: var = fH('siconc')
In [5]: x = vcs.init()
In [6]: y = vcs.init()
In [7]: x.meshfill(var)
Out[7]: <vcs.displayplot.Dp at 0x7f2a8d2a2050>
In [8]: y.meshfill(var)
Out[8]: <vcs.displayplot.Dp at 0x7f2ace8ce6e0>
In [9]: x.clear()
In [10]: y.clear()
In [11]: x.close() ; # This leads to a zombie window that doesn't die until the ipython session is killed
In [12]: y.close() ; #Same here
In [13]: import cdat_info
In [14]: cdat_info.version()
Out[14]: ['', '2.8.10']
```
And the file: 
[siconc_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-1_gn_187001.zip](https://github.com/UV-CDAT/vcs/files/991561/siconc_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-1_gn_187001.zip)

**Comment by durack1** [comment] 2017-05-11 01:38
@doutriaux1 is `cdat_info.version() - > ['', '2.8.10']` right? I thought the latest release should be `v2.10.0` instead..?

**Comment by doutriaux1** [comment] 2017-05-11 13:07
@durack1 nice catch I'll patch this, right away.

**Comment by doutriaux1** [comment] 2019-04-18 15:20
duplicate of https://github.com/CDAT/dv3d/issues/4

**Closed by doutriaux1** 2019-04-18 15:20 UTC
Labels: bug
