### ISSUE TITLE
wind barb support

### ISSUE THREAD

**Issue by chaosphere2112** [CDAT/vcs#90] opened 2016-11-23 16:17 UTC
vector.type= "barbs" should be drawing wind barbs

Migrated from: https://github.com/UV-CDAT/uvcdat/issues/1264

**Comment by doutriaux1** [comment] 2019-04-18 15:28
duplicate of: https://github.com/CDAT/vcs/issues/60

**Closed by doutriaux1** 2019-04-18 15:28 UTC
